### ISSUE TITLE
Old view with Swift

### ISSUE THREAD

**Issue by Madrox24** [TimOliver/TOSegmentedControl#11]
Hello, I'd love to use your SegmentedControl, but when I try add it by storyboard or programmatically in Swift I getting the same old view from iOS 12. 
Am I doing something wrong? Thank you for help.

**Comment by TimOliver** [comment]
Hi @Madrox24! Um really? It's called `SegmentedControl` in Swift. Are you sure you're creating the right object?

**Comment by Madrox24** [comment]
Yeah, with Objective-C all is working correctly, but with swift I can't get this new view of SegmentControl.

**Comment by TimOliver** [comment]
Sorry for the delay. Can you show me the code you’re using to instantiate the segmented control? I wonder if there’s a bug routing it to UISegmentedControl somehow.

**Comment by TimOliver** [comment]
I'm not sure what I can do to fix this. I'd need reproducible steps to see if there's actually an issue on my end.

Closing this off for now. Please open a new issue and provide either a sample app, or some sample code demonstrating the problem.

Thanks!
