### ISSUE TITLE
Swift package doesn't work.

### ISSUE THREAD

**Issue by skywinder** [TimOliver/TOSegmentedControl#15]
I tried to install it via SPM, didn't add any extra line of code and got error: 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3356474/74603222-e780d600-50e3-11ea-922d-e90733ef72cf.png">
<img width="677" alt="Screenshot 2020-02-16 at 17 44 49" src="https://user-images.githubusercontent.com/3356474/74603235-097a5880-50e4-11ea-858c-6ddc7d7b6def.png">

**Comment by skywinder** [comment]
Xcode Version 11.3.1 (11C504)

**Comment by skywinder** [comment]
To tell the truth, I got many similar issues with my packages, that I try to port to SPM. Just wondering, did you have any luck to run it?

**Comment by TimOliver** [comment]
Hi @skywinder! Yeah, I was keeping track of this. You might have noticed I already had an issue open for supporting SPM (https://github.com/TimOliver/TOSegmentedControl/issues/3).

This is an issue I've been getting on a lot of my libraries. An Apple engineer has advised me that it probably requires implementing a manual umbrella header to fix properly. In any case, I haven't had time to look into it.

Feel free to contribute to that first SPM issue if you find anything new that can help.

Thanks! :)
