### ISSUE TITLE
Fails on iOS 10

### ISSUE THREAD

**Issue by vicmosin** [TimOliver/TOSegmentedControl#31]
First of all, thanks for introducing this lib.
It's working as expected at iOS 14, but at virtual device on iOS 10 seems to not working. Maybe it's somehow related to #11 

Steps to reproduce:
1. Create the app, put standard segment control via storyboard
2. Run the app in iphone 7 iOS 10 simulator
3. Expected segment control to have same style as on iOS13/14, but it's not
4. Perform the same step and run at IOS 14 - works as expected, control has proper styling

According to docs though, it should work since iOS 9. Or is this indeed expected?

**Comment by TimOliver** [comment]
Sorry for the delay @vicmosin! Thanks for providing reproduction steps!

I just tested the sample app on an iPhone 5s running iOS 9 and it runs fine for me.

![IMG_0002](https://user-images.githubusercontent.com/429119/150668140-910b548a-8d66-4911-8122-bf9c270648af.PNG)

The sample app uses a storyboard, so I wonder if it's something with how you've configured the storyboard in your own app. In any case, at the moment, I'm not convinced this is an issue on my end.

If you're still having this problem, please open a new issue and provide a sample project I can test with. Thanks! :)
